name: Deployment
on:
    push:
        branches:
            - master
jobs:
    test:
        environment: testing
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-deps-${{ hashFiles('./06_starting_project/**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
              working-directory: ./06_starting_project
            - name: Run server
              run: npm start & npx wait-on http://127.0.0.1:XYZ
              working-directory: ./06_starting_project
            - name: Run tests
              run: npm test
              working-directory: ./06_starting_project
            - name: Output information
              run: echo "..."
              working-directory: ./06_starting_project
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: |
                  echo "..."
              working-directory: ./06_starting_project
