name: Display Issue Information 04
on: issues
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Print Issue Info
              run: |
                  echo "Issue Title: ${{ toJson(github.event) }}"
