name: 'Test Project'
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./02_starting_project
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
